#!/usr/bin/env python3
"""Generate an optional StrictDoc traceability projection from canonical docs/fable JSON.

The adapter never treats StrictDoc as an authority. It reads Fable schema-v2
requirements/plan/tests and writes only under docs/fable/derived/strictdoc/.
"""
import argparse
import datetime as dt
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

from fable_guard import canonical_digest, load_json, validate_core_docs, write_json_atomic

STRICTDOC_TARGET_VERSION = '0.30.1'
SUPPORTED_REPORT_SUFFIXES = (
    '.pytest.junit.xml',
    '.ctest.junit.xml',
    '.gtest.junit.xml',
    '.lit.junit.xml',
    '.nextest.junit.xml',
    '.robot.xml',
)


def derived_root(project: Path) -> Path:
    return project / 'docs' / 'fable' / 'derived' / 'strictdoc'


def load_canonical(project: Path):
    docs = project / 'docs' / 'fable'
    requirements = load_json(docs / 'requirements.json')
    plan = load_json(docs / 'plan.json')
    tests = load_json(docs / 'tests.json')
    core = validate_core_docs(project, requirements, plan, tests)
    if core['errors']:
        raise ValueError('\n'.join(core['errors']))
    basis = {
        'requirements_digest': canonical_digest(requirements),
        'plan_digest': canonical_digest(plan),
        'tests_digest': canonical_digest(tests),
    }
    return requirements, plan, tests, core, basis


def safe_statement(text: str) -> str:
    lines = str(text).splitlines() or ['']
    if any(line.strip() in {'<<<', '>>>'} for line in lines):
        raise ValueError('E_STRICTDOC_TEXT: requirement text contains reserved multiline delimiter line')
    return 'STATEMENT: >>>\n' + '\n'.join(lines) + '\n<<<'


def relation_key(link):
    return (
        link.get('path'),
        link.get('function'),
        link.get('class'),
        tuple(link.get('line_range') or ()),
    )


def render_file_relations(links):
    output = []
    seen = set()
    for link in links:
        key = relation_key(link)
        if key in seen:
            continue
        seen.add(key)
        output.extend([
            '- TYPE: File',
            f"  VALUE: {link['path']}",
        ])
        if link.get('function'):
            output.append(f"  FUNCTION: {link['function']}")
        if link.get('class'):
            output.append(f"  CLASS: {link['class']}")
        if link.get('line_range'):
            start, end = link['line_range']
            output.append(f'  LINE_RANGE: {start}, {end}')
    return output


def test_links_for_ids(test_catalog, test_ids):
    links = []
    for test_id in test_ids:
        test = test_catalog.get(test_id) or {}
        links.extend(test.get('source_links') or [])
    return links


def render_requirement(uid, title, statement, parent_uid=None, source_links=None):
    lines = [
        '[REQUIREMENT]',
        f'UID: {uid}',
        f'TITLE: {title}',
        safe_statement(statement),
    ]
    relations = []
    if parent_uid:
        relations.extend([
            '- TYPE: Parent',
            f'  VALUE: {parent_uid}',
        ])
    relations.extend(render_file_relations(source_links or []))
    if relations:
        lines.append('RELATIONS:')
        lines.extend(relations)
    return '\n'.join(lines)


def render_sdoc(requirements, tests):
    test_catalog = {row['id']: row for row in tests['tests']}
    chunks = [
        '[DOCUMENT]',
        'TITLE: Fable Derived Requirements',
        'UID: FABLE-DERIVED-REQUIREMENTS',
        '',
        '[TEXT]',
        'STATEMENT: >>>',
        'GENERATED FILE. docs/fable JSON remains authoritative. Regenerate; do not edit this file manually.',
        '<<<',
        '',
    ]
    for req in requirements['requirements']:
        req_links = [*(req.get('source_links') or []), *test_links_for_ids(test_catalog, req.get('test_ids') or [])]
        chunks.append(render_requirement(
            req['id'],
            req['id'],
            req['text'],
            source_links=req_links,
        ))
        chunks.append('')
        for criterion in req.get('criteria') or []:
            criterion_links = [
                *(criterion.get('source_links') or []),
                *test_links_for_ids(test_catalog, criterion.get('test_ids') or []),
            ]
            chunks.append(render_requirement(
                criterion['id'],
                f"Acceptance criterion {criterion['id']}",
                criterion['text'],
                parent_uid=req['id'],
                source_links=criterion_links,
            ))
            chunks.append('')
    return '\n'.join(chunks).rstrip() + '\n'


def render_config():
    # The generated StrictDoc project lives four levels below the repository root:
    # docs/fable/derived/strictdoc -> ../../../..
    return '''from strictdoc.core.project_config import ProjectConfig\n\n\ndef create_config() -> ProjectConfig:\n    return ProjectConfig(\n        project_title="Fable Derived Traceability",\n        project_features=[\n            "REQUIREMENT_TO_SOURCE_TRACEABILITY",\n        ],\n        source_root_path="../../../..",\n        include_doc_paths=[\n            "/*.sdoc",\n            "/reports/**",\n        ],\n    )\n'''


def file_sha(path: Path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def copy_supported_reports(project: Path, out: Path):
    source = project / 'reports'
    dest = out / 'reports'
    if dest.exists():
        shutil.rmtree(dest)
    copied = []
    if not source.is_dir():
        return copied
    for path in sorted(p for p in source.rglob('*') if p.is_file()):
        if not path.name.endswith(SUPPORTED_REPORT_SUFFIXES):
            continue
        rel = path.relative_to(project).as_posix()
        dest_rel = path.relative_to(source)
        target = dest / dest_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)
        copied.append(rel)
    return copied


def generate(project: Path):
    requirements, plan, tests, _, basis = load_canonical(project)
    del plan
    out = derived_root(project)
    out.mkdir(parents=True, exist_ok=True)
    sdoc_path = out / 'requirements.sdoc'
    config_path = out / 'strictdoc_config.py'
    sdoc_path.write_text(render_sdoc(requirements, tests), encoding='utf-8')
    config_path.write_text(render_config(), encoding='utf-8')
    copied_reports = copy_supported_reports(project, out)
    manifest = {
        'schema': 2,
        'generated_at': dt.datetime.now(dt.timezone.utc).isoformat(),
        'authority': 'docs/fable',
        'strictdoc_target_version': STRICTDOC_TARGET_VERSION,
        'basis': basis,
        'copied_reports': copied_reports,
        'projection_files': {
            'requirements.sdoc': file_sha(sdoc_path),
            'strictdoc_config.py': file_sha(config_path),
        },
    }
    write_json_atomic(out / 'manifest.json', manifest)
    return out, manifest


def check_projection(project: Path):
    _, _, _, _, basis = load_canonical(project)
    out = derived_root(project)
    manifest_path = out / 'manifest.json'
    if not manifest_path.is_file():
        return ['STRICTDOC_PROJECTION_MISSING: manifest.json not found']
    manifest = load_json(manifest_path)
    previous = manifest.get('basis') or {}
    changed = []
    if previous.get('requirements_digest') != basis['requirements_digest']:
        changed.append('requirements')
    if previous.get('plan_digest') != basis['plan_digest']:
        changed.append('plan')
    if previous.get('tests_digest') != basis['tests_digest']:
        changed.append('tests')
    errors = []
    if changed:
        errors.append('STRICTDOC_PROJECTION_STALE: ' + ', '.join(changed))
    for rel, expected in (manifest.get('projection_files') or {}).items():
        path = out / rel
        if not path.is_file():
            errors.append(f'STRICTDOC_PROJECTION_MISSING: {rel}')
        elif file_sha(path) != expected:
            errors.append(f'STRICTDOC_PROJECTION_TAMPERED: {rel}')
    return errors


def runtime_status():
    executable = shutil.which('strictdoc')
    if not executable:
        print('STRICTDOC_UNAVAILABLE: strictdoc CLI is not installed or not on PATH')
        return 3
    proc = subprocess.run([executable, '--version'], text=True, capture_output=True)
    if proc.returncode != 0:
        print('STRICTDOC_UNAVAILABLE: strictdoc CLI was found but --version failed')
        if proc.stderr:
            print(proc.stderr.strip())
        return 3
    version = (proc.stdout or proc.stderr).strip()
    print(f'STRICTDOC_AVAILABLE: {version or executable}')
    return 0


def main():
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest='command', required=True)
    for name in ('generate', 'check', 'runtime-status'):
        cmd = sub.add_parser(name)
        cmd.add_argument('--project', required=True)
    args = parser.parse_args()
    project = Path(args.project).resolve()
    try:
        if args.command == 'generate':
            out, _ = generate(project)
            print(f'STRICTDOC_PROJECTION_GENERATED: {out}')
            return 0
        if args.command == 'check':
            errors = check_projection(project)
            if errors:
                for error in errors:
                    print(error)
                return 1
            print('STRICTDOC_PROJECTION_CURRENT')
            return 0
        return runtime_status()
    except ValueError as exc:
        print(str(exc))
        return 2


if __name__ == '__main__':
    sys.exit(main())
